"use client";
import Link from "next/link";
import { useState } from "react";
import { Activity, ArrowUpRight, MessageCircle, ShieldCheck, ClipboardCheck } from "lucide-react";
import { PremiumHeader, PremiumFooter } from "@/components/PremiumSite";
import { useWhatsAppUrl } from "@/lib/whatsapp";
import { useSede } from "@/lib/sede";
export default function MuevetePremium() {
  const [profile,setProfile]=useState("persona");
  const [region,setRegion]=useState("Pachuca");
  const sede=useSede();
  const message=`Hola, quiero solicitar información para ingresar a Muévete Seguro. Perfil: ${profile === "persona" ? "Persona activa" : "Centro deportivo"}. Zona: ${region}. Me gustaría conocer cómo funciona, el costo y la disponibilidad.`;
  const href=useWhatsAppUrl(message,"tula");
  return <div className="premium"><PremiumHeader sede={sede}/><main className="p-wrap p-program-page"><section className="p-program-intro"><div><p className="p-eyebrow">MUÉVETE SEGURO · BY ORTIK</p><h1>Muévete.<br/>Entrena.<br/><em>Siéntete acompañado.</em></h1><p>Un programa de seguimiento de molestias y lesiones por WhatsApp, con supervisión médica. Para personas activas y centros deportivos que quieren cuidar mejor su movimiento.</p><a href="#solicitud" className="p-button p-button-light">Solicitar ingreso <ArrowUpRight size={18}/></a><p className="p-micro">Conoce las condiciones y disponibilidad antes de inscribirte.</p></div><div className="p-program-art" aria-hidden="true"><div/><div/><div/><Activity size={80} strokeWidth={1}/><span>MUÉVETE<br/><em>SEGURO.</em></span></div></section>
    <section className="p-program-points" aria-label="Qué ofrece el programa"><div><MessageCircle/><h3>Un canal cercano.</h3><p>Seguimiento por WhatsApp para comunicar cómo evolucionan tus molestias.</p></div><div><ShieldCheck/><h3>Supervisión médica.</h3><p>Las decisiones clínicas corresponden al médico. El programa no sustituye una consulta.</p></div><div><ClipboardCheck/><h3>Un siguiente paso.</h3><p>Conoce cuándo corresponde una valoración presencial y cómo continuar tu atención.</p></div></section>
    <section className="p-section p-application" id="solicitud"><div><p className="p-eyebrow">SOLICITUD DE INGRESO</p><h2>Cuidar tu movimiento<br/><em>empieza aquí.</em></h2><p>Cuéntanos qué perfil tienes y en qué zona estás. Nuestro equipo te explicará cómo funciona el programa y los pasos para ingresar.</p><p>No necesitas compartir datos clínicos en este formulario. La solicitud continúa por WhatsApp.</p><Link href="/muevete-seguro/atletas" className="p-text-link">Información para deportistas <ArrowUpRight size={15}/></Link><br/><br/><Link href="/centros-deportivos" className="p-text-link">Información para centros deportivos <ArrowUpRight size={15}/></Link></div><div className="p-application-form"><fieldset><legend>Quiero información para</legend><div className="p-choice-row"><label className="p-choice"><input type="radio" name="profile" value="persona" checked={profile === "persona"} onChange={() => setProfile("persona")}/>Mí</label><label className="p-choice"><input type="radio" name="profile" value="centro" checked={profile === "centro"} onChange={() => setProfile("centro")}/>Mi centro deportivo</label></div></fieldset><label htmlFor="program-region">Mi zona</label><select id="program-region" value={region} onChange={e => setRegion(e.target.value)}><option>Pachuca</option><option>Tula</option><option>Otra zona</option></select><a href={href} target="_blank" rel="noopener noreferrer" className="p-button p-button-contact" data-program="muevete_seguro" data-placement="application">Continuar por WhatsApp <ArrowUpRight size={18}/></a><p>Se abrirá un mensaje con tu selección. Envíalo para que nuestro equipo reciba la solicitud. Esto no confirma una inscripción ni realiza un cobro.</p><Link href="/privacidad" className="p-text-link">Aviso de privacidad</Link></div></section></main><PremiumFooter/></div>;
}
